language: cpp

# Compiler selection
compiler:
  - clang
  - gcc


# Build steps
script: 
  - apt-get install libgtest-dev
  - cd /usr/src/gtest
  - cmake CMakeLists.txt
  - make
  - cp *.a /usr/lib
  - cd ${TRAVIS_BUILD_DIR}
  - cmake .
  - make
  - ./tests
