language: cpp

before_script: 
- cd ${TRAVIS_BUILD_DIR}

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

# Compiler selection
compiler:
  - clang
  - gcc


# Build steps
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - cmake .
  - make
